theme: jekyll-theme-midnight
lang: en
timezone: Europe/Amsterdam
# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Polysance # the main title
tagline: Academic Pages for Polysance # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  Polysance is .
url: "https://polysance.github.io"
pageviews:
  provider: # now only supports 'goatcounter'
theme_mode: dark